name: mindful_minutes_example
description: Demonstrates how to use the mindful_minutes plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  mindful_minutes:
    path: ../

dev_dependencies:
  flutter_lints: '>=2.0.0 <5.0.0'
  flutter_test:
    sdk: flutter
