name: mindful_minutes
description: A Flutter plugin for saving mindful minutes to Apple Health.
version: 0.1.2
homepage: https://github.com/nohli/mindful_minutes

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MindfulMinutesPlugin
