name: mindful_minutes
description: A Flutter package for saving mindful minutes to Apple Health.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    pluginClass: MindfulMinutesPlugin
