name: mindful_minutes
description: A Flutter plugin for saving mindful minutes to Apple Health.

repository: https://github.com/nohli/mindful_minutes
issue_tracker: https://github.com/nohli/mindful_minutes/issues

version: 1.0.2+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MindfulMinutesPlugin
