name: Flutter build example

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_ios:
    name: Build example for iOS
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Disable analytics
        run: flutter config --no-analytics
      - name: Flutter pub get
        run: flutter pub get
      - name: Pod install
        run: |
          cd example
          cd ios
          pod install
      - name: Flutter build iOS
        run: |
          cd example
          flutter build ios --release --no-codesign
