name: Integration Tests (iOS)

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/dependabot.yml'
      - '.github/workflows/flutter_build_example.yml'
      - '.github/workflows/flutter_checks.yml'
      - '.github/workflows/pub_publish.yml'
      - '.github/workflows/pub_publish_dry_run.yml'
      - '.github/workflows/pub_score.yml'
      - 'analysis_options.yaml'
      - 'test/**'
      - 'example/analysis_options.yaml'
      - 'example/integration_test/unsupported_platform_integration_test.dart'
      - 'example/test/**'
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/dependabot.yml'
      - '.github/workflows/flutter_build_example.yml'
      - '.github/workflows/flutter_checks.yml'
      - '.github/workflows/pub_publish.yml'
      - '.github/workflows/pub_publish_dry_run.yml'
      - '.github/workflows/pub_score.yml'
      - 'analysis_options.yaml'
      - 'test/**'
      - 'example/analysis_options.yaml'
      - 'example/integration_test/unsupported_platform_integration_test.dart'
      - 'example/test/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration_test_ios:
    name: iOS ${{ matrix.os-version }} - ${{ matrix.model }}
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/futureware-tech/simulator-action/wiki/Devices-macos-latest
        os-version: ['26.2']
        model: ['iPhone 17']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Boot iOS simulator
        id: boot_simulator
        uses: futureware-tech/simulator-action@v5
        with:
          os_version: ${{ matrix.os-version }}
          model: ${{ matrix.model }}
          wait_for_boot: true

      - name: Run integration tests on iOS
        # Flutter can intermittently hang after the Xcode build while waiting
        # for the VM service: https://github.com/flutter/flutter/issues/181771
        timeout-minutes: 15
        run: |
          cd example
          flutter test integration_test -d "${{ steps.boot_simulator.outputs.udid }}"
