name: Pub publish dry run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-dry-run:
    name: Pub publish dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Publish dry run
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          credentialJson: 'MockCredentialJson'
          dryRunOnly: true
